Docs
GMLC-TDC/HELICS pull request #2225
Opened 2021-12-07 17:50 UTC by trevorhardy

### Summary

If merged this pull request will update the documentation to remove/correct references to the Fundamental Final example.

### Proposed changes

Update documentation TOCs and links

2021-12-07 18:11 UTC, nightlark commented on docs/build_RTD.sh
> +python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
Fixes the shellcheck error about not knowing what the shell syntax to lint against.

```suggestion
#!/bin/sh
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
```

2021-12-07 19:56 UTC, phlptp approved these changes

2021-12-10 19:06 UTC, nightlark requested changes

2021-12-10 19:06 UTC, nightlark commented on docs/build_RTD.sh
> +python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
After this precommit fix is made the PR can be merged. It could also be /bin/bash instead.

2021-12-14 01:50 UTC, trevorhardy reviewed
All looks good to me. @nightlark, ready for your approval, I think.

2021-12-14 20:04 UTC, nightlark approved these changes

2021-12-14 20:40 UTC, trevorhardy commented
@nightlark or @phlptp, the "Merge pull request" button on Github is grayed out for me with a corresponding message "Required status must pass before merging." Is there something else I need to do to merge this?

2021-12-14 21:02 UTC, merged

2021-12-14 21:05 UTC, nightlark commented
@trevorhardy it's just one of the intermittent CI tests failing... just need to rerun the failing required check until it passes